### ISSUE TITLE
"Unable to post message to http://www.youtube.com" JavaScript error

### ISSUE THREAD

**Issue by zvineyard** [sanderheilbron/youtube.ga.js#3]
When working in Chrome, I get this message repeated 6 times when using the default installation of your script: "Unable to post message to http://www.youtube.com. Recipient has origin http://www.my-domain.com." Any ideas what might be causing errors? It looks like a cross-domain request is getting filtered, but I still get the tracking results in Analytics.

**Comment by sanderheilbron** [comment]
Please check this discussion:
https://groups.google.com/d/msg/youtube-api-gdata/VKGl4ahBGyk/nCiL7oK35twJ

> The error message about mismatched domains is harmless, and it's due to this bug in WebKit:
> 
>  http://code.google.com/p/chromium/issues/detail?id=17325
